/**
 * Postgres baseline schema — the Postgres-equivalent END STATE of
 * server/src/db/schema.ts + all 207 SQLite migration steps in
 * server/src/db/migrations.ts, produced by introspecting a live SQLite
 * instance's sqlite_master (after createTables + runMigrations) and
 * hand-translating the dialect differences. This is a BASELINE, not a
 * step-by-step transliteration of migrations.ts: SQLite-only workarounds
 * (e.g. the `PRAGMA foreign_keys=OFF` create-copy-drop-rename dance
 * migrations.ts uses to change a column's type, since SQLite has no
 * `ALTER COLUMN`) have no Postgres equivalent and are already resolved into
 * this end-state DDL directly — Postgres's native `ALTER TABLE ... ALTER
 * COLUMN` replaces that whole pattern going forward.
 *
 * Table order matters: unlike SQLite, Postgres requires a REFERENCES target
 * to already exist at CREATE TABLE time, so these are topologically sorted
 * by foreign-key dependency (verified by applying this file's DDL to a real
 * Postgres 17 instance end-to-end with zero errors — see
 * postgres-schema.test.ts).
 *
 * Type mapping decisions:
 *  - `INTEGER PRIMARY KEY AUTOINCREMENT` -> `INTEGER GENERATED BY DEFAULT AS
 *    IDENTITY PRIMARY KEY` — BY DEFAULT, not ALWAYS, deliberately: it accepts
 *    an explicit id on INSERT without needing `OVERRIDING SYSTEM VALUE`,
 *    exactly like SQLite's AUTOINCREMENT already does. This is load-bearing
 *    for the one-time import tool (migrate-sqlite-to-postgres.ts), which must
 *    preserve every row's original id so existing foreign keys still resolve;
 *    it costs nothing in normal operation because no application call site
 *    ever supplies an explicit id on insert today.
 *  - Boolean-flag columns stay INTEGER (0/1), not converted to BOOLEAN — this
 *    avoids touching every truthy-check read site in the same migration
 *    milestone that's already converting sync SQL calls to async.
 *  - `REAL` -> `DOUBLE PRECISION`, `BLOB` -> `BYTEA`.
 *  - Every column identified as a timestamp is `TIMESTAMPTZ`: an explicit
 *    SQLite `DATETIME` column (`DEFAULT CURRENT_TIMESTAMP` -> `DEFAULT
 *    now()`), an INTEGER column defaulted via `strftime('%s','now')`
 *    (epoch seconds — only `idempotency_keys.created_at`), a TEXT column
 *    defaulted via `datetime('now')` (a handful of `plugin_*` audit/cache
 *    tables), or an INTEGER column hand-verified (by reading its writer in
 *    src/nest/**) to hold epoch MILLISECONDS despite no SQL-level default —
 *    see EPOCH_MS_COLUMNS in the generation notes below. Those millisecond
 *    columns get no DB-level DEFAULT here, matching today's behavior where
 *    the app always supplies `Date.now()` explicitly on insert.
 *  - A handful of TEXT columns are known to sometimes hold an
 *    application-generated ISO-8601 string (e.g. oauth.service.ts,
 *    trip-invite.service.ts) but could not be positively identified from the
 *    DDL alone across all ~390 TEXT columns in this schema — those are
 *    conservatively left as TEXT rather than guessed at. Storing an ISO
 *    string in TEXT is correct and loses no data; it just isn't natively
 *    TIMESTAMPTZ-typed yet. A follow-up per-column audit can promote specific
 *    columns later without a data migration (TEXT and TIMESTAMPTZ round-trip
 *    the same ISO representation).
 *
 * Columns hand-verified to hold epoch MILLISECONDS (declared INTEGER in
 * SQLite, TIMESTAMPTZ here): google_place_photo_meta.{fetched_at,error_at},
 * journey_contributors.added_at, journey_entries.{created_at,updated_at},
 * journey_entry_photos.created_at, journey_photos.created_at,
 * journey_trips.added_at, journeys.{created_at,updated_at},
 * place_details_cache.fetched_at, plugin_oauth_state.created_at,
 * plugin_oauth_tokens.expires_at, plugin_scheduled_tasks.due_at,
 * trek_photo_cache_meta.fetched_at, user_notice_dismissals.dismissed_at,
 * webauthn_challenges.expires_at. idempotency_keys.created_at is the one
 * exception stored in epoch SECONDS (`strftime('%s','now')`) rather than
 * milliseconds — also TIMESTAMPTZ here. The one-time import tool
 * (migrate-sqlite-to-postgres.ts) is what actually reconciles the stored
 * values into real timestamps; this file only declares the target column
 * types.
 *
 * `migrations` (near the middle of the list below) is a vestigial fossil
 * table — a SQLite CREATE-TABLE DDL literally matching TypeORM's default
 * migrations-table shape, left over from an early prototype. It is
 * write-only (one seed INSERT in migrations.ts, never read by any app code)
 * and carried through here unchanged for schema fidelity, not because
 * anything depends on it.
 *
 * One table from the live introspection is DELIBERATELY excluded:
 * `schema_version`. In SQLite it tracks the OLD migration system's own
 * bookkeeping (which of the 207 steps in migrations.ts have run) — that
 * number is meaningless once the app runs on Postgres, and re-creating it
 * here would collide with migrations.pg.ts's own `schema_version` table
 * (which tracks *this* file's PG_MIGRATIONS array instead, starting fresh at
 * the baseline). The one-time import tool does not copy this table's row.
 */

export const POSTGRES_BASELINE_TABLES: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS addons (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      type TEXT NOT NULL DEFAULT 'global',
      icon TEXT DEFAULT 'Puzzle',
      enabled INTEGER DEFAULT 0,
      config TEXT DEFAULT '{}',
      sort_order INTEGER DEFAULT 0
    )`,
  `CREATE TABLE IF NOT EXISTS app_settings (
      key TEXT PRIMARY KEY,
      value TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT UNIQUE NOT NULL,
      email TEXT UNIQUE NOT NULL,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user',
      maps_api_key TEXT,
      unsplash_api_key TEXT,
      openweather_api_key TEXT,
      avatar TEXT,
      oidc_sub TEXT,
      oidc_issuer TEXT,
      last_login TIMESTAMPTZ,
      mfa_enabled INTEGER DEFAULT 0,
      mfa_secret TEXT,
      mfa_backup_codes TEXT,
      immich_url TEXT,
      immich_access_token TEXT,
      synology_url TEXT,
      synology_username TEXT,
      synology_password TEXT,
      synology_sid TEXT,
      must_change_password INTEGER DEFAULT 0,
      password_version INTEGER NOT NULL DEFAULT 0,
      feed_token TEXT,
      is_guest INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    , immich_api_key TEXT, synology_skip_ssl INTEGER NOT NULL DEFAULT 0, synology_did TEXT, first_seen_version TEXT NOT NULL DEFAULT '0.0.0', login_count INTEGER NOT NULL DEFAULT 0, immich_auto_upload INTEGER NOT NULL DEFAULT 0, airtrail_url TEXT, airtrail_api_key TEXT, airtrail_allow_insecure_tls INTEGER DEFAULT 0, airtrail_write_enabled INTEGER DEFAULT 0, display_name TEXT)`,
  `CREATE TABLE IF NOT EXISTS trips (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      description TEXT,
      start_date TEXT,
      end_date TEXT,
      currency TEXT DEFAULT 'EUR',
      cover_image TEXT,
      is_archived INTEGER DEFAULT 0,
      reminder_days INTEGER DEFAULT 3,
      feed_token TEXT,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS days (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      day_number INTEGER NOT NULL,
      date TEXT,
      notes TEXT,
      title TEXT, default_transport_mode TEXT,
      UNIQUE(trip_id, day_number)
    )`,
  `CREATE TABLE IF NOT EXISTS categories (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      color TEXT DEFAULT '#6366f1',
      icon TEXT DEFAULT '📍',
      user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS places (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      description TEXT,
      lat DOUBLE PRECISION,
      lng DOUBLE PRECISION,
      address TEXT,
      category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
      price DOUBLE PRECISION,
      currency TEXT,
      reservation_status TEXT DEFAULT 'none',
      reservation_notes TEXT,
      reservation_datetime TEXT,
      place_time TEXT,
      end_time TEXT,
      duration_minutes INTEGER DEFAULT 60,
      notes TEXT,
      image_url TEXT,
      google_place_id TEXT,
      google_ftid TEXT,
      website TEXT,
      phone TEXT,
      transport_mode TEXT DEFAULT 'walking',
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    , osm_id TEXT, route_geometry TEXT, route_color TEXT)`,
  `CREATE TABLE IF NOT EXISTS day_assignments (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      day_id INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE,
      place_id INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE,
      order_index INTEGER DEFAULT 0,
      notes TEXT,
      reservation_status TEXT DEFAULT 'none',
      reservation_notes TEXT,
      reservation_datetime TEXT,
      created_at TIMESTAMPTZ DEFAULT now()
    , assignment_time TEXT, assignment_end_time TEXT, leg_transport_mode TEXT, incoming_leg_transport_mode TEXT)`,
  `CREATE TABLE IF NOT EXISTS assignment_participants (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      assignment_id INTEGER NOT NULL REFERENCES day_assignments(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      UNIQUE(assignment_id, user_id)
    )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMPTZ DEFAULT now(),
      user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      action TEXT NOT NULL,
      resource TEXT,
      details TEXT,
      ip TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS bucket_list (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        lat DOUBLE PRECISION,
        lng DOUBLE PRECISION,
        country_code TEXT,
        notes TEXT,
        created_at TIMESTAMPTZ DEFAULT now()
      , target_date TEXT DEFAULT NULL)`,
  `CREATE TABLE IF NOT EXISTS budget_category_order (
          trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
          category TEXT NOT NULL,
          sort_order INTEGER NOT NULL DEFAULT 0,
          PRIMARY KEY (trip_id, category)
        )`,
  `CREATE TABLE IF NOT EXISTS reservations (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      day_id INTEGER REFERENCES days(id) ON DELETE SET NULL,
      end_day_id INTEGER REFERENCES days(id) ON DELETE SET NULL,
      place_id INTEGER REFERENCES places(id) ON DELETE SET NULL,
      assignment_id INTEGER REFERENCES day_assignments(id) ON DELETE SET NULL,
      title TEXT NOT NULL,
      accommodation_id TEXT,
      reservation_time TEXT,
      reservation_end_time TEXT,
      location TEXT,
      confirmation_number TEXT,
      notes TEXT,
      status TEXT DEFAULT 'pending',
      type TEXT DEFAULT 'other',
      created_at TIMESTAMPTZ DEFAULT now()
    , metadata TEXT, day_plan_position DOUBLE PRECISION DEFAULT NULL, needs_review INTEGER NOT NULL DEFAULT 0, external_source TEXT, external_id TEXT, external_owner_user_id INTEGER, external_synced_at TEXT, sync_enabled INTEGER DEFAULT 1, external_hash TEXT, url TEXT, ingest_state TEXT NOT NULL DEFAULT 'live')`,
  `CREATE TABLE IF NOT EXISTS budget_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      category TEXT NOT NULL DEFAULT 'Other',
      name TEXT NOT NULL,
      total_price DOUBLE PRECISION NOT NULL DEFAULT 0,
      persons INTEGER DEFAULT NULL,
      days INTEGER DEFAULT NULL,
      note TEXT,
      currency TEXT DEFAULT NULL,
      exchange_rate DOUBLE PRECISION DEFAULT 1.0,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now()
    , paid_by_user_id INTEGER REFERENCES users(id), expense_date TEXT DEFAULT NULL, reservation_id INTEGER REFERENCES reservations(id) ON DELETE SET NULL DEFAULT NULL, ticket_json TEXT, place_id INTEGER REFERENCES places(id) ON DELETE SET NULL DEFAULT NULL)`,
  `CREATE TABLE IF NOT EXISTS budget_item_members (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          budget_item_id INTEGER NOT NULL REFERENCES budget_items(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          paid INTEGER NOT NULL DEFAULT 0, amount DOUBLE PRECISION,
          UNIQUE(budget_item_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS budget_item_payers (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          budget_item_id INTEGER NOT NULL REFERENCES budget_items(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          amount DOUBLE PRECISION NOT NULL DEFAULT 0,
          UNIQUE(budget_item_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS budget_settlements (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
          from_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          to_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          amount DOUBLE PRECISION NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ DEFAULT now(),
          created_by_user_id INTEGER REFERENCES users(id)
        , currency TEXT, exchange_rate DOUBLE PRECISION NOT NULL DEFAULT 1)`,
  `CREATE TABLE IF NOT EXISTS collab_messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      text TEXT NOT NULL,
      reply_to INTEGER REFERENCES collab_messages(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ DEFAULT now()
    , deleted INTEGER DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS collab_message_reactions (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          message_id INTEGER NOT NULL REFERENCES collab_messages(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          emoji TEXT NOT NULL,
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE(message_id, user_id, emoji)
        )`,
  `CREATE TABLE IF NOT EXISTS collab_notes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      category TEXT DEFAULT 'General',
      title TEXT NOT NULL,
      content TEXT,
      color TEXT DEFAULT '#6366f1',
      pinned INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    , website TEXT)`,
  `CREATE TABLE IF NOT EXISTS collab_polls (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      question TEXT NOT NULL,
      options TEXT NOT NULL,
      multiple INTEGER DEFAULT 0,
      closed INTEGER DEFAULT 0,
      deadline TEXT,
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS collab_poll_votes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      poll_id INTEGER NOT NULL REFERENCES collab_polls(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      option_index INTEGER NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(poll_id, user_id, option_index)
    )`,
  `CREATE TABLE IF NOT EXISTS collections (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      description TEXT,
      color TEXT DEFAULT '#6366f1',
      icon TEXT DEFAULT 'Bookmark',
      cover_image TEXT,
      links TEXT,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS collection_labels (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      color TEXT DEFAULT '#6366f1',
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS collection_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      status TEXT NOT NULL DEFAULT 'pending',
      role TEXT NOT NULL DEFAULT 'editor',
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(collection_id, user_id)
    )`,
  `CREATE TABLE IF NOT EXISTS collection_places (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
      owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      saved_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
      name TEXT NOT NULL,
      description TEXT,
      lat DOUBLE PRECISION,
      lng DOUBLE PRECISION,
      address TEXT,
      category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
      price DOUBLE PRECISION,
      currency TEXT,
      notes TEXT,
      image_url TEXT,
      google_place_id TEXT,
      google_ftid TEXT,
      osm_id TEXT,
      website TEXT,
      phone TEXT,
      status TEXT NOT NULL DEFAULT 'idea',
      source_trip_id INTEGER,
      source_place_id INTEGER,
      links TEXT,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now(),
      updated_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS collection_place_labels (
      collection_place_id INTEGER NOT NULL REFERENCES collection_places(id) ON DELETE CASCADE,
      label_id INTEGER NOT NULL REFERENCES collection_labels(id) ON DELETE CASCADE,
      PRIMARY KEY (collection_place_id, label_id)
    )`,
  `CREATE TABLE IF NOT EXISTS collection_place_ratings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      collection_place_id INTEGER NOT NULL REFERENCES collection_places(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      rating INTEGER NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(collection_place_id, user_id)
    )`,
  `CREATE TABLE IF NOT EXISTS tags (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      color TEXT DEFAULT '#10b981',
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS collection_place_tags (
      collection_place_id INTEGER NOT NULL REFERENCES collection_places(id) ON DELETE CASCADE,
      tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
      PRIMARY KEY (collection_place_id, tag_id)
    )`,
  `CREATE TABLE IF NOT EXISTS day_accommodations (
          id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          trip_id      INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
          place_id     INTEGER REFERENCES places(id) ON DELETE SET NULL,
          start_day_id INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE,
          end_day_id   INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE,
          check_in     TEXT,
          check_in_end TEXT,
          check_out    TEXT,
          confirmation TEXT,
          notes        TEXT,
          created_at   TIMESTAMPTZ DEFAULT now()
        )`,
  `CREATE TABLE IF NOT EXISTS day_notes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      day_id INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      text TEXT NOT NULL,
      time TEXT,
      icon TEXT DEFAULT '📝',
      sort_order DOUBLE PRECISION DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now()
    , color TEXT)`,
  `CREATE TABLE IF NOT EXISTS trip_files (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      place_id INTEGER REFERENCES places(id) ON DELETE SET NULL,
      reservation_id INTEGER REFERENCES reservations(id) ON DELETE SET NULL,
      filename TEXT NOT NULL,
      original_name TEXT NOT NULL,
      file_size INTEGER,
      mime_type TEXT,
      description TEXT,
      created_at TIMESTAMPTZ DEFAULT now()
    , note_id INTEGER REFERENCES collab_notes(id) ON DELETE SET NULL, uploaded_by INTEGER REFERENCES users(id) ON DELETE SET NULL, starred INTEGER DEFAULT 0, deleted_at TEXT)`,
  `CREATE TABLE IF NOT EXISTS file_links (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        file_id INTEGER NOT NULL REFERENCES trip_files(id) ON DELETE CASCADE,
        reservation_id INTEGER REFERENCES reservations(id) ON DELETE CASCADE,
        assignment_id INTEGER REFERENCES day_assignments(id) ON DELETE CASCADE,
        place_id INTEGER REFERENCES places(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(file_id, reservation_id),
        UNIQUE(file_id, assignment_id),
        UNIQUE(file_id, place_id)
      )`,
  `CREATE TABLE IF NOT EXISTS google_place_photo_meta (
          place_id   TEXT    PRIMARY KEY,
          attribution TEXT,
          fetched_at TIMESTAMPTZ NOT NULL,
          error_at TIMESTAMPTZ
        )`,
  `CREATE TABLE IF NOT EXISTS hidden_countries (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          country_code TEXT NOT NULL,
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE (user_id, country_code)
        )`,
  `CREATE TABLE IF NOT EXISTS hidden_regions (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          region_code TEXT NOT NULL,
          country_code TEXT NOT NULL,
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE (user_id, region_code)
        )`,
  `CREATE TABLE IF NOT EXISTS idempotency_keys (
          key         TEXT NOT NULL,
          user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          method      TEXT NOT NULL,
          path        TEXT NOT NULL,
          status_code INTEGER NOT NULL,
          response_body TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (key, user_id, method, path)
        )`,
  `CREATE TABLE IF NOT EXISTS invite_tokens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        token TEXT UNIQUE NOT NULL,
        max_uses INTEGER NOT NULL DEFAULT 1,
        used_count INTEGER NOT NULL DEFAULT 0,
        expires_at TEXT,
        created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ DEFAULT now()
      , trip_id INTEGER REFERENCES trips(id) ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS journeys (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL,
          title TEXT NOT NULL,
          subtitle TEXT,
          cover_gradient TEXT,
          status TEXT DEFAULT 'draft',
          created_at TIMESTAMPTZ NOT NULL,
          updated_at TIMESTAMPTZ NOT NULL, cover_image TEXT, show_trip_tracks INTEGER NOT NULL DEFAULT 0,
          FOREIGN KEY (user_id) REFERENCES users(id)
        )`,
  `CREATE TABLE IF NOT EXISTS journey_books (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          journey_id INTEGER NOT NULL REFERENCES journeys(id) ON DELETE CASCADE,
          title TEXT NOT NULL DEFAULT '',
          document TEXT NOT NULL,
          version INTEGER NOT NULL DEFAULT 1,
          created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
          updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
          created_at TIMESTAMPTZ DEFAULT now(),
          updated_at TIMESTAMPTZ DEFAULT now()
        )`,
  `CREATE TABLE IF NOT EXISTS journey_contributors (
          journey_id INTEGER NOT NULL,
          user_id INTEGER NOT NULL,
          role TEXT NOT NULL,
          added_at TIMESTAMPTZ NOT NULL, hide_skeletons INTEGER NOT NULL DEFAULT 0,
          PRIMARY KEY (journey_id, user_id),
          FOREIGN KEY (journey_id) REFERENCES journeys(id) ON DELETE CASCADE,
          FOREIGN KEY (user_id) REFERENCES users(id)
        )`,
  `CREATE TABLE IF NOT EXISTS journey_entries (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          journey_id INTEGER NOT NULL,
          source_trip_id INTEGER,
          source_place_id INTEGER,
          author_id INTEGER NOT NULL,
          type TEXT NOT NULL,
          title TEXT,
          story TEXT,
          entry_date TEXT NOT NULL,
          entry_time TEXT,
          location_name TEXT,
          location_lat DOUBLE PRECISION,
          location_lng DOUBLE PRECISION,
          mood TEXT,
          weather TEXT,
          tags TEXT,
          visibility TEXT DEFAULT 'private',
          sort_order INTEGER DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL,
          updated_at TIMESTAMPTZ NOT NULL, pros_cons TEXT, stats_excluded INTEGER NOT NULL DEFAULT 0,
          FOREIGN KEY (journey_id) REFERENCES journeys(id) ON DELETE CASCADE,
          FOREIGN KEY (source_trip_id) REFERENCES trips(id) ON DELETE SET NULL,
          FOREIGN KEY (source_place_id) REFERENCES places(id) ON DELETE SET NULL,
          FOREIGN KEY (author_id) REFERENCES users(id)
        )`,
  `CREATE TABLE IF NOT EXISTS trek_photos (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          provider TEXT NOT NULL,
          asset_id TEXT,
          owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
          file_path TEXT,
          thumbnail_path TEXT,
          width INTEGER,
          height INTEGER,
          created_at TIMESTAMPTZ DEFAULT now()
        , passphrase TEXT DEFAULT NULL, media_type TEXT NOT NULL DEFAULT 'image', duration_ms INTEGER, taken_at TEXT, lat DOUBLE PRECISION, lng DOUBLE PRECISION)`,
  `CREATE TABLE IF NOT EXISTS journey_photos (
          id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          journey_id  INTEGER NOT NULL REFERENCES journeys(id)    ON DELETE CASCADE,
          photo_id    INTEGER NOT NULL REFERENCES trek_photos(id) ON DELETE CASCADE,
          caption     TEXT,
          shared      INTEGER DEFAULT 0,
          sort_order  INTEGER DEFAULT 0,
          provider    TEXT,
          asset_id    TEXT,
          owner_id    INTEGER,
          created_at TIMESTAMPTZ NOT NULL,
          UNIQUE(journey_id, photo_id)
        )`,
  `CREATE TABLE IF NOT EXISTS journey_entry_photos (
          entry_id          INTEGER NOT NULL REFERENCES journey_entries(id) ON DELETE CASCADE,
          journey_photo_id  INTEGER NOT NULL REFERENCES journey_photos(id)  ON DELETE CASCADE,
          sort_order        INTEGER DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL,
          PRIMARY KEY(entry_id, journey_photo_id)
        )`,
  `CREATE TABLE IF NOT EXISTS journey_share_tokens (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          journey_id INTEGER NOT NULL,
          token TEXT NOT NULL UNIQUE,
          created_by INTEGER NOT NULL,
          share_timeline INTEGER DEFAULT 1,
          share_gallery INTEGER DEFAULT 1,
          share_map INTEGER DEFAULT 1,
          created_at TIMESTAMPTZ DEFAULT now(), newest_first INTEGER NOT NULL DEFAULT 0,
          FOREIGN KEY (journey_id) REFERENCES journeys(id) ON DELETE CASCADE,
          FOREIGN KEY (created_by) REFERENCES users(id)
        )`,
  `CREATE TABLE IF NOT EXISTS journey_trips (
          journey_id INTEGER NOT NULL,
          trip_id INTEGER NOT NULL,
          added_at TIMESTAMPTZ NOT NULL,
          PRIMARY KEY (journey_id, trip_id),
          FOREIGN KEY (journey_id) REFERENCES journeys(id) ON DELETE CASCADE,
          FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE
        )`,
  `CREATE TABLE IF NOT EXISTS mcp_tokens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        token_hash TEXT NOT NULL,
        token_prefix TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT now(),
        last_used_at TIMESTAMPTZ
      , kind TEXT NOT NULL DEFAULT 'mcp')`,
  `CREATE TABLE IF NOT EXISTS migrations (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL, timestamp bigint NOT NULL, name varchar NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS notification_channel_preferences (
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      event_type TEXT NOT NULL,
      channel TEXT NOT NULL,
      enabled INTEGER NOT NULL DEFAULT 1,
      PRIMARY KEY (user_id, event_type, channel)
    )`,
  `CREATE TABLE IF NOT EXISTS notifications (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type TEXT NOT NULL CHECK(type IN ('simple', 'boolean', 'navigate')),
      scope TEXT NOT NULL CHECK(scope IN ('trip', 'user', 'admin')),
      target INTEGER NOT NULL,
      sender_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
      recipient_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      title_key TEXT NOT NULL,
      title_params TEXT DEFAULT '{}',
      text_key TEXT NOT NULL,
      text_params TEXT DEFAULT '{}',
      positive_text_key TEXT,
      negative_text_key TEXT,
      positive_callback TEXT,
      negative_callback TEXT,
      response TEXT CHECK(response IN ('positive', 'negative')),
      navigate_text_key TEXT,
      navigate_target TEXT,
      is_read INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS oauth_clients (
                id                 TEXT PRIMARY KEY,
                user_id            INTEGER REFERENCES users(id) ON DELETE CASCADE,
                name               TEXT NOT NULL,
                client_id          TEXT UNIQUE NOT NULL,
                client_secret_hash TEXT NOT NULL,
                redirect_uris      TEXT NOT NULL DEFAULT '[]',
                allowed_scopes     TEXT NOT NULL DEFAULT '[]',
                created_at         TIMESTAMPTZ DEFAULT now(),
                is_public          INTEGER NOT NULL DEFAULT 0,
                created_via        TEXT NOT NULL DEFAULT 'settings_ui'
              , allows_client_credentials INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS oauth_consents (
          id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          client_id  TEXT NOT NULL REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
          user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          scopes     TEXT NOT NULL DEFAULT '[]',
          updated_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE(client_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS oauth_tokens (
          id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          client_id                 TEXT NOT NULL REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
          user_id                   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          access_token_hash         TEXT UNIQUE NOT NULL,
          refresh_token_hash        TEXT UNIQUE NOT NULL,
          scopes                    TEXT NOT NULL DEFAULT '[]',
          access_token_expires_at   TIMESTAMPTZ NOT NULL,
          refresh_token_expires_at  TIMESTAMPTZ NOT NULL,
          revoked_at                TIMESTAMPTZ,
          created_at                TIMESTAMPTZ DEFAULT now()
        , parent_token_id INTEGER REFERENCES oauth_tokens(id), audience TEXT)`,
  `CREATE TABLE IF NOT EXISTS packing_bags (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        color TEXT NOT NULL DEFAULT '#6366f1',
        weight_limit_grams INTEGER,
        sort_order INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now()
      , user_id INTEGER REFERENCES users(id) ON DELETE SET NULL DEFAULT NULL)`,
  `CREATE TABLE IF NOT EXISTS packing_bag_members (
          bag_id INTEGER NOT NULL REFERENCES packing_bags(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          PRIMARY KEY (bag_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS packing_category_assignees (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
        category_name TEXT NOT NULL,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        UNIQUE(trip_id, category_name, user_id)
      )`,
  `CREATE TABLE IF NOT EXISTS packing_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      checked INTEGER DEFAULT 0,
      category TEXT,
      sort_order INTEGER DEFAULT 0,
      created_at TIMESTAMPTZ DEFAULT now()
    , weight_grams INTEGER, bag_id INTEGER REFERENCES packing_bags(id) ON DELETE SET NULL, quantity INTEGER NOT NULL DEFAULT 1, updated_at TIMESTAMPTZ, is_private INTEGER NOT NULL DEFAULT 0, owner_id INTEGER REFERENCES users(id) ON DELETE SET NULL)`,
  `CREATE TABLE IF NOT EXISTS packing_item_contributors (
          item_id INTEGER NOT NULL REFERENCES packing_items(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          status TEXT NOT NULL DEFAULT 'accepted',
          created_at TIMESTAMPTZ DEFAULT now(),
          PRIMARY KEY (item_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS packing_item_recipients (
          item_id INTEGER NOT NULL REFERENCES packing_items(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          PRIMARY KEY (item_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS packing_templates (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        created_at TIMESTAMPTZ DEFAULT now()
      )`,
  `CREATE TABLE IF NOT EXISTS packing_template_categories (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        template_id INTEGER NOT NULL REFERENCES packing_templates(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0
      )`,
  `CREATE TABLE IF NOT EXISTS packing_template_items (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category_id INTEGER NOT NULL REFERENCES packing_template_categories(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0
      )`,
  `CREATE TABLE IF NOT EXISTS password_reset_tokens (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token_hash TEXT NOT NULL UNIQUE,
      expires_at TIMESTAMPTZ NOT NULL,
      consumed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ DEFAULT now(),
      created_ip TEXT
    )`,
  `CREATE TABLE IF NOT EXISTS photo_providers (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      description TEXT,
      icon TEXT DEFAULT 'Image',
      enabled INTEGER DEFAULT 0,
      sort_order INTEGER DEFAULT 0
    )`,
  `CREATE TABLE IF NOT EXISTS photo_provider_fields (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      provider_id TEXT NOT NULL REFERENCES photo_providers(id) ON DELETE CASCADE,
      field_key TEXT NOT NULL,
      label TEXT NOT NULL,
      input_type TEXT NOT NULL DEFAULT 'text',
      placeholder TEXT,
      hint TEXT,
      required INTEGER DEFAULT 0,
      secret INTEGER DEFAULT 0,
      settings_key TEXT,
      payload_key TEXT,
      sort_order INTEGER DEFAULT 0,
      UNIQUE(provider_id, field_key)
    )`,
  `CREATE TABLE IF NOT EXISTS photos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      day_id INTEGER REFERENCES days(id) ON DELETE SET NULL,
      place_id INTEGER REFERENCES places(id) ON DELETE SET NULL,
      filename TEXT NOT NULL,
      original_name TEXT NOT NULL,
      file_size INTEGER,
      mime_type TEXT,
      caption TEXT,
      taken_at TEXT,
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS place_details_cache (
          place_id   TEXT    NOT NULL,
          lang       TEXT    NOT NULL DEFAULT '',
          expanded   INTEGER NOT NULL DEFAULT 0,
          payload_json TEXT  NOT NULL,
          fetched_at TIMESTAMPTZ NOT NULL,
          PRIMARY KEY (place_id, lang, expanded)
        )`,
  `CREATE TABLE IF NOT EXISTS place_ratings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      place_id INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      rating INTEGER NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(place_id, user_id)
    )`,
  `CREATE TABLE IF NOT EXISTS place_regions (
          place_id INTEGER PRIMARY KEY REFERENCES places(id) ON DELETE CASCADE,
          country_code TEXT NOT NULL,
          region_code TEXT NOT NULL,
          region_name TEXT NOT NULL
        )`,
  `CREATE TABLE IF NOT EXISTS place_tags (
      place_id INTEGER NOT NULL REFERENCES places(id) ON DELETE CASCADE,
      tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
      PRIMARY KEY (place_id, tag_id)
    )`,
  `CREATE TABLE IF NOT EXISTS plugin_actions (
          plugin_id TEXT NOT NULL,
          action_key TEXT NOT NULL,
          label TEXT NOT NULL,
          hint TEXT,
          danger INTEGER NOT NULL DEFAULT 0,
          sort_order INTEGER NOT NULL DEFAULT 0, scope TEXT NOT NULL DEFAULT 'user',
          PRIMARY KEY (plugin_id, action_key)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_capability_audit (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          acting_user_id INTEGER,
          method TEXT NOT NULL,
          resource TEXT,
          code TEXT NOT NULL,
          ts TIMESTAMPTZ NOT NULL DEFAULT now(),
          prev_hash TEXT,
          hash TEXT NOT NULL
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_egress_hosts (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          host TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (plugin_id, host)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_entity_metadata (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        plugin_id TEXT NOT NULL,
        entity_type TEXT NOT NULL,
        entity_id INTEGER NOT NULL,
        key TEXT NOT NULL,
        value TEXT,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (plugin_id, entity_type, entity_id, key)
      )`,
  `CREATE TABLE IF NOT EXISTS plugin_error_log (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          ts TIMESTAMPTZ DEFAULT now(),
          level TEXT NOT NULL DEFAULT 'error',
          message TEXT,
          stack TEXT
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_meta_migrations (
          plugin_id TEXT NOT NULL,
          migration_id TEXT NOT NULL,
          applied_at TIMESTAMPTZ DEFAULT now(),
          PRIMARY KEY (plugin_id, migration_id)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_oauth_state (
          state TEXT PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          user_id INTEGER NOT NULL,
          verifier TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_oauth_tokens (
          plugin_id TEXT NOT NULL,
          user_id INTEGER NOT NULL,
          access_token TEXT,
          refresh_token TEXT,
          expires_at TIMESTAMPTZ,
          scope TEXT,
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (plugin_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_scheduled_tasks (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          name TEXT NOT NULL,
          due_at TIMESTAMPTZ NOT NULL,
          payload TEXT NOT NULL DEFAULT 'null',
          every_ms INTEGER,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (plugin_id, name)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_settings_fields (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          field_key TEXT NOT NULL,
          label TEXT,
          input_type TEXT NOT NULL DEFAULT 'text',
          placeholder TEXT,
          hint TEXT,
          required INTEGER NOT NULL DEFAULT 0,
          secret INTEGER NOT NULL DEFAULT 0,
          scope TEXT NOT NULL DEFAULT 'instance',
          options TEXT,
          oauth_config TEXT,
          sort_order INTEGER NOT NULL DEFAULT 0, default_value TEXT,
          UNIQUE (plugin_id, field_key)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_user_config (
          plugin_id TEXT NOT NULL,
          user_id INTEGER NOT NULL,
          config TEXT NOT NULL DEFAULT '{}',
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          PRIMARY KEY (plugin_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS plugin_user_erasure_queue (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          plugin_id TEXT NOT NULL,
          user_id INTEGER NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          UNIQUE (plugin_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS plugins (
          id TEXT PRIMARY KEY,
          name TEXT NOT NULL,
          description TEXT,
          type TEXT NOT NULL DEFAULT 'integration',
          icon TEXT DEFAULT 'Blocks',
          version TEXT,
          api_version INTEGER DEFAULT 1,
          min_trek_version TEXT,
          permissions TEXT DEFAULT '[]',
          granted_permissions TEXT DEFAULT '[]',
          status TEXT NOT NULL DEFAULT 'inactive',
          config TEXT DEFAULT '{}',
          source_repo TEXT,
          source_commit TEXT,
          sha256 TEXT,
          crash_count INTEGER NOT NULL DEFAULT 0,
          last_error TEXT,
          reviewed_at TEXT,
          sort_order INTEGER NOT NULL DEFAULT 0,
          installed_at TIMESTAMPTZ DEFAULT now(),
          updated_at TIMESTAMPTZ DEFAULT now()
        , enabled INTEGER NOT NULL DEFAULT 0, capabilities TEXT NOT NULL DEFAULT '{}', author_pubkey TEXT, dependencies TEXT NOT NULL DEFAULT '{}', operator_egress INTEGER NOT NULL DEFAULT 0, update_block_code TEXT, update_block_detail TEXT, update_block_version TEXT, trek_range TEXT, update_hold INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS reservation_day_positions (
          reservation_id INTEGER NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
          day_id INTEGER NOT NULL REFERENCES days(id) ON DELETE CASCADE,
          position DOUBLE PRECISION NOT NULL,
          PRIMARY KEY (reservation_id, day_id)
        )`,
  `CREATE TABLE IF NOT EXISTS reservation_endpoints (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reservation_id INTEGER NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
          role TEXT NOT NULL,
          sequence INTEGER NOT NULL DEFAULT 0,
          name TEXT NOT NULL,
          code TEXT,
          lat DOUBLE PRECISION NOT NULL,
          lng DOUBLE PRECISION NOT NULL,
          timezone TEXT,
          local_time TEXT,
          local_date TEXT,
          created_at TIMESTAMPTZ DEFAULT now()
        )`,
  `CREATE TABLE IF NOT EXISTS reservation_travelers (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reservation_id INTEGER NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          UNIQUE(reservation_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS settings (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      key TEXT NOT NULL,
      value TEXT,
      UNIQUE(user_id, key)
    )`,
  `CREATE TABLE IF NOT EXISTS share_tokens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
        token TEXT NOT NULL UNIQUE,
        created_by INTEGER NOT NULL REFERENCES users(id),
        share_map INTEGER DEFAULT 1,
        share_bookings INTEGER DEFAULT 1,
        share_packing INTEGER DEFAULT 0,
        share_budget INTEGER DEFAULT 0,
        share_collab INTEGER DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT now()
      , expires_at TEXT)`,
  `CREATE TABLE IF NOT EXISTS todo_category_assignees (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
          category_name TEXT NOT NULL,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          UNIQUE(trip_id, category_name, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS todo_items (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
          name TEXT NOT NULL,
          checked INTEGER DEFAULT 0,
          category TEXT,
          sort_order INTEGER DEFAULT 0,
          due_date TEXT,
          description TEXT,
          assigned_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
          priority INTEGER DEFAULT 0,
          created_at TIMESTAMPTZ DEFAULT now()
        , reminded_at TIMESTAMPTZ)`,
  `CREATE TABLE IF NOT EXISTS trek_photo_cache_meta (
        cache_key  TEXT    PRIMARY KEY,
        content_type TEXT  NOT NULL DEFAULT 'image/jpeg',
        fetched_at TIMESTAMPTZ NOT NULL
      )`,
  `CREATE TABLE IF NOT EXISTS trip_album_links (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
              user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              provider TEXT NOT NULL,
              album_id TEXT NOT NULL,
              album_name TEXT NOT NULL DEFAULT '',
              sync_enabled INTEGER NOT NULL DEFAULT 1,
              last_synced_at TIMESTAMPTZ,
              created_at TIMESTAMPTZ DEFAULT now(), passphrase TEXT DEFAULT NULL,
              UNIQUE(trip_id, user_id, provider, album_id)
            )`,
  `CREATE TABLE IF NOT EXISTS trip_invite_tokens (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          trip_id INTEGER NOT NULL UNIQUE REFERENCES trips(id) ON DELETE CASCADE,
          token TEXT UNIQUE NOT NULL,
          created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,
          expires_at TEXT,
          created_at TIMESTAMPTZ DEFAULT now()
        )`,
  `CREATE TABLE IF NOT EXISTS trip_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      invited_by INTEGER REFERENCES users(id),
      added_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(trip_id, user_id)
    )`,
  `CREATE TABLE IF NOT EXISTS trip_photos (
              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              trip_id INTEGER NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
              user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
              photo_id INTEGER NOT NULL REFERENCES trek_photos(id) ON DELETE CASCADE,
              shared INTEGER NOT NULL DEFAULT 1,
              album_link_id INTEGER REFERENCES trip_album_links(id) ON DELETE SET NULL,
              added_at TIMESTAMPTZ DEFAULT now(),
              UNIQUE(trip_id, user_id, photo_id)
            )`,
  `CREATE TABLE IF NOT EXISTS user_notice_dismissals (
          user_id      INTEGER NOT NULL,
          notice_id    TEXT    NOT NULL,
          dismissed_at TIMESTAMPTZ NOT NULL, dismissed_app_version TEXT,
          PRIMARY KEY (user_id, notice_id),
          FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )`,
  `CREATE TABLE IF NOT EXISTS vacay_plans (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      block_weekends INTEGER DEFAULT 1,
      holidays_enabled INTEGER DEFAULT 0,
      holidays_region TEXT DEFAULT '',
      school_holidays_enabled INTEGER DEFAULT 0,
      company_holidays_enabled INTEGER DEFAULT 1,
      carry_over_enabled INTEGER DEFAULT 1,
      created_at TIMESTAMPTZ DEFAULT now(), weekend_days TEXT DEFAULT '0,6', week_start INTEGER NOT NULL DEFAULT 1,
      UNIQUE(owner_id)
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_company_holidays (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      plan_id INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      date TEXT NOT NULL,
      note TEXT DEFAULT '',
      UNIQUE(plan_id, date)
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_entries (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      plan_id INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      date TEXT NOT NULL,
      note TEXT DEFAULT '', fraction DOUBLE PRECISION NOT NULL DEFAULT 1, kind TEXT NOT NULL DEFAULT 'vacation',
      UNIQUE(user_id, plan_id, date)
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_holiday_calendars (
      id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      plan_id   INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      type      TEXT NOT NULL DEFAULT 'public_holiday',
      region    TEXT NOT NULL,
      label     TEXT,
      color     TEXT NOT NULL DEFAULT '#fecaca',
      sort_order INTEGER NOT NULL DEFAULT 0
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_plan_members (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      plan_id INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      status TEXT DEFAULT 'pending',
      created_at TIMESTAMPTZ DEFAULT now(),
      UNIQUE(plan_id, user_id)
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_shares (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          owner_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          hidden INTEGER NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE (owner_id, user_id)
        )`,
  `CREATE TABLE IF NOT EXISTS vacay_user_colors (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      plan_id INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      color TEXT DEFAULT '#6366f1',
      UNIQUE(user_id, plan_id)
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_user_settings (
          user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
          year_type TEXT NOT NULL DEFAULT 'calendar',
          year_start_month INTEGER NOT NULL DEFAULT 1,
          year_start_day INTEGER NOT NULL DEFAULT 1,
          hire_date TEXT
        )`,
  `CREATE TABLE IF NOT EXISTS vacay_user_years (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      plan_id INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      year INTEGER NOT NULL,
      vacation_days INTEGER DEFAULT 30,
      carried_over INTEGER DEFAULT 0,
      UNIQUE(user_id, plan_id, year)
    )`,
  `CREATE TABLE IF NOT EXISTS vacay_years (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      plan_id INTEGER NOT NULL REFERENCES vacay_plans(id) ON DELETE CASCADE,
      year INTEGER NOT NULL,
      UNIQUE(plan_id, year)
    )`,
  `CREATE TABLE IF NOT EXISTS visited_countries (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        country_code TEXT NOT NULL,
        created_at TIMESTAMPTZ DEFAULT now(),
        UNIQUE(user_id, country_code)
      )`,
  `CREATE TABLE IF NOT EXISTS visited_regions (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          region_code TEXT NOT NULL,
          region_name TEXT NOT NULL,
          country_code TEXT NOT NULL,
          created_at TIMESTAMPTZ DEFAULT now(),
          UNIQUE(user_id, region_code)
        )`,
  `CREATE TABLE IF NOT EXISTS webauthn_challenges (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      challenge TEXT NOT NULL UNIQUE,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ DEFAULT now()
    )`,
  `CREATE TABLE IF NOT EXISTS webauthn_credentials (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      credential_id TEXT NOT NULL UNIQUE,
      public_key BYTEA NOT NULL,
      counter INTEGER NOT NULL DEFAULT 0,
      transports TEXT,
      device_type TEXT,
      backed_up INTEGER NOT NULL DEFAULT 0,
      name TEXT,
      aaguid TEXT,
      created_at TIMESTAMPTZ DEFAULT now(),
      last_used_at TIMESTAMPTZ
    )`,
];

export const POSTGRES_BASELINE_INDEXES: readonly string[] = [
  `CREATE INDEX IF NOT EXISTS idx_assignment_participants_assignment ON assignment_participants(assignment_id)`,
  `CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_budget_item_members_item ON budget_item_members(budget_item_id)`,
  `CREATE INDEX IF NOT EXISTS idx_budget_item_members_user ON budget_item_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_budget_item_payers_item ON budget_item_payers(budget_item_id)`,
  `CREATE INDEX IF NOT EXISTS idx_budget_items_trip_id ON budget_items(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_budget_settlements_trip ON budget_settlements(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collab_messages_trip ON collab_messages(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collab_notes_trip ON collab_notes(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collab_polls_trip ON collab_polls(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collab_reactions_msg ON collab_message_reactions(message_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_labels_collection ON collection_labels(collection_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_members_user ON collection_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_place_labels_label ON collection_place_labels(label_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_place_labels_place ON collection_place_labels(collection_place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_place_ratings_place ON collection_place_ratings (collection_place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_place_tags_place ON collection_place_tags(collection_place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_place_tags_tag ON collection_place_tags(tag_id)`,
  `CREATE INDEX IF NOT EXISTS idx_collection_places_collection ON collection_places(collection_id)`,
  `CREATE INDEX IF NOT EXISTS idx_day_accommodations_end_day_id ON day_accommodations(end_day_id)`,
  `CREATE INDEX IF NOT EXISTS idx_day_accommodations_start_day_id ON day_accommodations(start_day_id)`,
  `CREATE INDEX IF NOT EXISTS idx_day_accommodations_trip_id ON day_accommodations(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_day_assignments_day_id ON day_assignments(day_id)`,
  `CREATE INDEX IF NOT EXISTS idx_day_assignments_place_id ON day_assignments(place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_day_notes_day_id ON day_notes(day_id)`,
  `CREATE INDEX IF NOT EXISTS idx_days_trip_id ON days(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_hidden_countries_user ON hidden_countries (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_hidden_regions_user ON hidden_regions (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_idempotency_keys_created ON idempotency_keys(created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_books_journey ON journey_books(journey_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_contributors_user ON journey_contributors(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_entries_journey ON journey_entries(journey_id, entry_date)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_entries_order ON journey_entries(journey_id, entry_date, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_entries_source ON journey_entries(source_place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_entry_photos_entry   ON journey_entry_photos(entry_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_entry_photos_photo   ON journey_entry_photos(journey_photo_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_photos_journey       ON journey_photos(journey_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journey_trips_journey ON journey_trips(journey_id)`,
  `CREATE INDEX IF NOT EXISTS idx_journeys_user ON journeys(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_ncp_user ON notification_channel_preferences(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_id, is_read, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created ON notifications(recipient_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_notifications_target_scope ON notifications(target, scope)`,
  `CREATE INDEX IF NOT EXISTS idx_oauth_clients_user ON oauth_clients(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_oauth_tokens_parent ON oauth_tokens(parent_token_id)`,
  `CREATE INDEX IF NOT EXISTS idx_oauth_tokens_user ON oauth_tokens(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_packing_bag_members_bag ON packing_bag_members(bag_id)`,
  `CREATE INDEX IF NOT EXISTS idx_packing_item_recipients_user ON packing_item_recipients(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_packing_items_trip_id ON packing_items(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_photos_day_id ON photos(day_id)`,
  `CREATE INDEX IF NOT EXISTS idx_photos_place_id ON photos(place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_photos_trip_id ON photos(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_place_ratings_place ON place_ratings (place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_place_regions_country ON place_regions(country_code)`,
  `CREATE INDEX IF NOT EXISTS idx_place_regions_region ON place_regions(region_code)`,
  `CREATE INDEX IF NOT EXISTS idx_place_tags_place_id ON place_tags(place_id)`,
  `CREATE INDEX IF NOT EXISTS idx_place_tags_tag_id ON place_tags(tag_id)`,
  `CREATE INDEX IF NOT EXISTS idx_places_category_id ON places(category_id)`,
  `CREATE INDEX IF NOT EXISTS idx_places_trip_id ON places(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_plugin_audit_plugin ON plugin_capability_audit (plugin_id, id)`,
  `CREATE INDEX IF NOT EXISTS idx_plugin_egress_hosts_plugin ON plugin_egress_hosts (plugin_id)`,
  `CREATE INDEX IF NOT EXISTS idx_plugin_erasure_plugin ON plugin_user_erasure_queue (plugin_id)`,
  `CREATE INDEX IF NOT EXISTS idx_plugin_error_log_plugin ON plugin_error_log(plugin_id, ts)`,
  `CREATE INDEX IF NOT EXISTS idx_plugin_meta_entity ON plugin_entity_metadata (plugin_id, entity_type, entity_id)`,
  `CREATE INDEX IF NOT EXISTS idx_plugin_sched_due ON plugin_scheduled_tasks (due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_prt_hash ON password_reset_tokens(token_hash)`,
  `CREATE INDEX IF NOT EXISTS idx_prt_user ON password_reset_tokens(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_reservation_endpoints_reservation_id ON reservation_endpoints(reservation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_reservation_travelers_res ON reservation_travelers(reservation_id)`,
  `CREATE INDEX IF NOT EXISTS idx_reservation_travelers_user ON reservation_travelers(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_reservations_day_id ON reservations(day_id)`,
  `CREATE INDEX IF NOT EXISTS idx_reservations_trip_id ON reservations(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_share_tokens_token ON share_tokens(token)`,
  `CREATE INDEX IF NOT EXISTS idx_todo_items_trip_id ON todo_items(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trek_photo_cache_meta_fetched_at ON trek_photo_cache_meta (fetched_at)`,
  `CREATE INDEX IF NOT EXISTS idx_trek_photos_geo ON trek_photos(lat, lng) WHERE lat IS NOT NULL AND lng IS NOT NULL`,
  `CREATE INDEX IF NOT EXISTS idx_trek_photos_owner ON trek_photos(owner_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_album_links_trip ON trip_album_links(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_files_trip_id ON trip_files(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_invite_tokens_token ON trip_invite_tokens(token)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_members_trip_id ON trip_members(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_members_user_id ON trip_members(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_photos_photo ON trip_photos(photo_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trip_photos_trip ON trip_photos(trip_id)`,
  `CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips(created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_trips_user_id ON trips(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)`,
  `CREATE INDEX IF NOT EXISTS idx_vacay_shares_user ON vacay_shares (user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_visited_regions_country ON visited_regions(country_code)`,
  `CREATE INDEX IF NOT EXISTS idx_webauthn_challenges_expires ON webauthn_challenges(expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_webauthn_credentials_user ON webauthn_credentials(user_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_journey_share_journey ON journey_share_tokens(journey_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_mcp_tokens_hash ON mcp_tokens(token_hash)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_clients_client_id ON oauth_clients(client_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_tokens_access  ON oauth_tokens(access_token_hash)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_oauth_tokens_refresh ON oauth_tokens(refresh_token_hash)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_reservations_external ON reservations(external_source, external_id, trip_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_trek_photos_provider_asset ON trek_photos(provider, asset_id, owner_id) WHERE asset_id IS NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_trips_feed_token ON trips(feed_token) WHERE feed_token IS NOT NULL`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_users_feed_token ON users(feed_token) WHERE feed_token IS NOT NULL`,
];

const TABLE_NAME_PATTERN = /CREATE TABLE IF NOT EXISTS ([a-z_0-9]+)/;

/**
 * Table names in the same FK-dependency order as POSTGRES_BASELINE_TABLES —
 * the single source of truth for "what order can I safely INSERT rows in"
 * (parents before children), used by the one-time import tool. Derived from
 * the DDL itself so it can never drift from the table list above.
 */
export function baselineTableNamesInDependencyOrder(): readonly string[] {
  return POSTGRES_BASELINE_TABLES.map((sql) => {
    const match = sql.match(TABLE_NAME_PATTERN);
    if (!match) throw new Error(`could not parse a table name out of: ${sql.slice(0, 80)}...`);
    return match[1];
  });
}
