apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.configmapName }}
  namespace: {{ .Values.config.namespace }}
data:
  NODE_ENV: "production"
  PORT: "{{ .Values.config.port }}"
  ALLOW_INTERNAL_NETWORK: "true"
  APP_URL: "https://{{ .Values.ingress.hostName }}"
