---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.ingressName }}
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.hostName }}
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.org/client-max-body-size: "500m"
spec:
  ingressClassName: nginx
  tls:
    - secretName: {{ .Values.ingress.tlsCertName }}
      hosts:
        - {{ .Values.ingress.hostName }}
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.serviceName }}
                port:
                  number: {{ .Values.config.port }}
