---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.secretName }}
  namespace: {{ .Values.config.namespace }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.secret.encryptedSecretData }}
  template:
    metadata:
      name: {{ .Values.secret.secretName }}
      namespace: {{ .Values.config.namespace }}
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.oidcSecretName }}
  namespace: {{ .Values.config.namespace }}
spec:
  encryptedData:
    OIDC_CLIENT_ID: {{ .Values.secret.encryptedOidcClientId }}
    OIDC_CLIENT_SECRET: {{ .Values.secret.encryptedOidcClientSecret }}
    OIDC_DISPLAY_NAME: {{ .Values.secret.encryptedOidcDisplayName }}
    OIDC_ISSUER: {{ .Values.secret.encryptedOidcIssuer }}
    OIDC_ONLY: {{ .Values.secret.encryptedOidcOnly }}
  template:
    metadata:
      name: oidc-trek-secret
      namespace: trek

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trek-pg
  namespace: trek
spec:
  encryptedData:
    adminPasswordKey: AgDSf2FY1xtYsU0M2PUCgqmzNhTbqB8LADW/USSUCJL2AOtvvP7buhj1TSoWMZ4D9yEEa+o5f3WYxL9QaP7Wp48Fa9vDNGKxR1cv2htcIu+7RUUXQBh/UcVbP/v9gXYIUhjtuIClFa6gBH3oIRPvUuHoUY1cLtWWk8GGfff1/L4Rqh7K3iqfJu/DOMLOSqQIBMV3BN0zilsLTY/7MOW23g7Zp1qLtwMXSr/FHRjfDVgWhO6RRn9vRXoz66piZbnEMKuK7XYEeR+nIDv+7odGdZi6mJ7vxpUvraMI9k2IgJhBkWX35Nn3y1Mz5gDkH301YJSuO/cT3IVcgKj37fgihw3zo1q8wKfMAkg0INCng0bY9Nhhb85TuktO2ZXHBTT/6/Upm6unKdBLIE8So+pB92UZCgCEsX6983b6dyD4CzHO5j5jtqY054G1hc5bmrB1OOIKXz4DqdS448giCJfwBAMq+9oYrLaqmoSiayDIBpmRDjnGk3Q8XSIqhfOgp48JK/oDFqn8GAFKVrlx2iyUQgEe7lFQ41dsGCPkD01+buBI388xtYkCKhiS23tXOIWfjIb2vDdlLjcLMBft030b4l6zLISeL+xpjaNMXCWYQhhIA91G7R4Sab15ycVN57oESFYe6Ik892calFJ5HlF3Tre2/qkp/jc2hsF46/uw6HEGlMnBAIf1ErB+QWdlAG656W3w52BQ10//4CmN0CA1h4kdJug3fFi3X5vHmiDCAQ+sgXg5nUcueya7IziF/KM=
    replicationPasswordKey: AgCMKUt2vdBfQUFV3iwEkiRkqRxSer0gM6VcYdscLe5bx0t09Mh7SQg6AHsrHKGDn0i7nwuS7kMWi2cYwG0AolnE+mV6CKNMWVdP4Wzhyg9To2QMpDbAiZL+vk9HaMxUc4HCKjUj/+sll5jUg0oJCMpTCfEjwvz0OAnWNS9LFnIT5Hxt/ExwhWRKERh/k7aiMVr5Cj2B6lsgV9ZCnyiprvDuHvvCFhB3jTJGLZ2t04B0HQmQlhwpX4lQQc4vSpRPDxP8rJfs+ysOO8myhFVaRsIIS1k6yc2FJ/7DbKVWbnXPRmNEs9sWw3Egm+adOuaOm2GVGwQxWFmk9c9hSUCloDGyxzqrFcD8muXW2gA3siAid5vcFHPcQw/qTyD/RX8zQR0TGGPJGM49dWm91z6q7LDF1wMjvXIwOOUx3Ba/uHSk4B+WDWI6szltRXpEfVqusluUFIXqcIF1uXaR1IY9v2s9yS6pPH4PxayIJNJGn2f48Ha/s8S/grUUN4edCC9zPa4rLL0RlELmuz06rlCavpbzEXSzo+g/pxXKM4W299UR9N5CDf2YamGdoLlDlASYiQZDVqFrbwjpPmL7/QSEHRnxbyqj5kuCX9vEIYLU5Hu/lcs/8rG+WyvOU0GztsV/qB1/v2vEyNzr9RCP8ShL+CCWShXD4UmV0xvAqb1MyTX1Al520sxSOcE/yWVLoARGBTqF58nsx7W8Wf5/UatqvtSAR1oYKq9hfTKW1zU72Yv3i62kxmJEFgTzQiekw2Q=
    userPasswordKey: AgC/RSZvZDyuLUBeXeTxjp8bqClRoX3dlZ4iMT0smxI0xh6uskSlFXOP9LknM658nTzditnEia1AuWGspnEHYKOKdO8J1ifirywFoCa70EeR6B50pJ5kbVgfbZFjWcB547osXFHqyQRQAHATavbjF58AyJGeCzxEvn2Ykzr5Djss06q/eG5S1U3UbvYVtzX7/FEiTJ45Ht/J3aL8Ka7yeuL3uFoZ1uOB4ozYyFBTq2cNzHhemATj6o59u2IFXjrrWmDyVgO6nEwrdL8xTDyN6QnCYyQsV2wagivZh0+Z5jLXAHs7iB6gJ9eZ63sEeIbhbiLvddNkQSiui1IjuKLQOT0i4amjULut9it1ambb+N0baXJaGCLqOT79NUQ1I+wo3vmcgmBw1lPQAYr6BMYl1dkSDQ7IAjfrJVR6bocl2h+GE+rti5Pmq8lr3u8AsUiJtsDomxQXlZhXsW9yvsyfm1wRHvBmM8E4s28t26l1sN6mWRJIGqJ0QAJgNidxjgQqaG0uu5Si00nyiX58eUKvHJNsAZsq9LeEEIE2SVMMEKZh3GbQh1/HWQDC48LaMqu3gSMD6uF/QgMX5kjy9MqXFbX3gn0pvt+gsrP+C50NBGtxdW/nnDtIZQCe9PNqQG5aeVVi6R5U9IhcDE0RNqat5f0FA58LIsD6vKjt368YchJu+ObyygHEvG2yQ4nN1lZobOpobSbrjWqr04Ix6YkbL4d8OEIvbVUUzSwC8IpiA0QqiZc4XQvf5gJzTO1KOCY=
  template:
    metadata:
      name: trek-pg
      namespace: trek
