---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.secretName }}
  namespace: {{ .Values.config.namespace }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.secret.encryptedSecretData }}
  template:
    metadata:
      name: {{ .Values.secret.secretName }}
      namespace: {{ .Values.config.namespace }}
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.oidcSecretName }}
  namespace: {{ .Values.config.namespace }}
spec:
  encryptedData:
    OIDC_CLIENT_ID: {{ .Values.secret.encryptedOidcClientId }}
    OIDC_CLIENT_SECRET: {{ .Values.secret.encryptedOidcClientSecret }}
    OIDC_DISPLAY_NAME: {{ .Values.secret.encryptedOidcDisplayName }}
    OIDC_ISSUER: {{ .Values.secret.encryptedOidcIssuer }}
    OIDC_ONLY: {{ .Values.secret.encryptedOidcOnly }}
  template:
    metadata:
      name: oidc-trek-secret
      namespace: trek
