---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secret.secretName }}
  namespace: {{ .Values.config.namespace }}
spec:
  encryptedData:
    JWT_SECRET: {{ .Values.secret.encryptedSecretData }}
  template:
    metadata:
      name: {{ .Values.secret.secretName }}
      namespace: {{ .Values.config.namespace }}
    type: Opaque
