---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.serviceName }}
  namespace: {{ .Values.config.namespace }}
spec:
  selector:
    app: {{ .Values.config.name }}
  ports:
    - port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
  type: ClusterIP
