apiVersion: v1
kind: Service
metadata:
  name: {{ include "airtrail.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "airtrail.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.airtrail.service.type }}
  ports:
    - port: {{ .Values.airtrail.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "airtrail.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: app
