{{- if .Values.db.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "airtrail.dbFullname" . }}-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "airtrail.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.db.persistence.storageClass }}
  storageClassName: {{ .Values.db.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size }}
{{- end }}
