apiVersion: v1
kind: Service
metadata:
  name: {{ include "airtrail.dbFullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "airtrail.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "airtrail.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
