{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airtrail.secretName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "airtrail.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORIGIN: {{ .Values.env.origin | quote }}
  DB_URL: {{ include "airtrail.dbUrl" . | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  DB_DATABASE_NAME: {{ .Values.env.dbDatabaseName | quote }}
  DB_USERNAME: {{ .Values.env.dbUsername | quote }}
  UPLOAD_LOCATION: {{ .Values.env.uploadLocation | quote }}
  BODY_SIZE_LIMIT: {{ .Values.env.bodySizeLimit | quote }}
  {{- if .Values.env.mapProvider }}
  MAP_PROVIDER: {{ .Values.env.mapProvider | quote }}
  {{- end }}
  {{- if .Values.env.mapCartoApiKey }}
  MAP_CARTO_API_KEY: {{ .Values.env.mapCartoApiKey | quote }}
  {{- end }}
  {{- if .Values.env.mapProtomapsSourceKind }}
  MAP_PROTOMAPS_SOURCE_KIND: {{ .Values.env.mapProtomapsSourceKind | quote }}
  {{- end }}
  {{- if .Values.env.mapProtomapsApiKey }}
  MAP_PROTOMAPS_API_KEY: {{ .Values.env.mapProtomapsApiKey | quote }}
  {{- end }}
  {{- if .Values.env.mapProtomapsSourceUrl }}
  MAP_PROTOMAPS_SOURCE_URL: {{ .Values.env.mapProtomapsSourceUrl | quote }}
  {{- end }}
  {{- if .Values.env.mapProtomapsMaxZoom }}
  MAP_PROTOMAPS_MAX_ZOOM: {{ .Values.env.mapProtomapsMaxZoom | quote }}
  {{- end }}
  {{- if .Values.env.mapProtomapsAssetsBaseUrl }}
  MAP_PROTOMAPS_ASSETS_BASE_URL: {{ .Values.env.mapProtomapsAssetsBaseUrl | quote }}
  {{- end }}
  {{- if .Values.env.mapProtomapsLanguage }}
  MAP_PROTOMAPS_LANGUAGE: {{ .Values.env.mapProtomapsLanguage | quote }}
  {{- end }}
  {{- if .Values.env.mapLightStyleUrl }}
  MAP_LIGHT_STYLE_URL: {{ .Values.env.mapLightStyleUrl | quote }}
  {{- end }}
  {{- if .Values.env.mapDarkStyleUrl }}
  MAP_DARK_STYLE_URL: {{ .Values.env.mapDarkStyleUrl | quote }}
  {{- end }}
{{- end }}
