config:
  name: trek
  namespace: trek
  imageName: docker.io/asdfghjklxd/trek
  imageTag: latest
  imagePullPolicy: Always
  port: 3000
  forceHttps: true

# Optional image pull secrets for private registries
imagePullSecrets: []
  # - name: my-registry-secret

app:
  replicas: 1

ingress:
  ingressName: trek-ingress
  tlsCertName: trek-tls
  hostName: trek.georgetay.com

service:
  serviceName: trek-service

configmap:
  configmapName: trek-config

secret:
  secretName: trek-secret
  encryptedSecretData: AgBegKtCopBrrbUwNNnsG/YeYvA29bChGycW0AqkRCoUGU9G419xPy+XI5iGKgPCa0K3eEM4tI6U+DEIIBuZo7hIbp0XFD9B7snt7Yf1Uq57DGH3DhrhZIgsrcieaimL8kmPs2p6C7ywOnuKwcXZPlcdKzNkZd7pUwiTpfyc3Lgw9LtKySowaha6qNP+Ek2rKCefC6lL5hlIvBF3che3azzlKpbM0RyKFB0zVbNuRoH6kIvEoHejaP0/Ol4JZP8OzbhI2zRBwtVpWl50I3fO+dIuNmU6w8TsCjgYJJeBs5CTJJj9bHSRFOIyKHeVYEWruQjm4k7j8czD9SIwghwbpOtGWSUlOqL2aS0nDHjlMFURLvB5t2zABho0uWpoPnl9bXOYVBUAvBHmCiCtkzU5kppGmvfQUuRNrbhP8q3Pz6viKgcbJ4s7f8LFH0M0x+gM5/HAWozDnlDkiD9k9FejIFbAYjXIHkSzRay/VptxIyjYFjiS5s4Mt/0jM8FP6P5sqRN881b8CpcS/KUXUdtVD6gNq4z2h8a51FoC2t5LbmOLQTAmc8Snh6dO++48XV2xnvWCARaYHz+cKbuC2t0K3RjajyWyhaWLkKUrPM/9bnd4Duxz/01KSnacVV2MikU/WDSWel6vI6+hySothEuwmsshyX6U8zKWPKvwKiRWouw8frNaHvzHJBdFyHvAfpauNQXEmTCeWU3R8OAR1teebvMI9eQIK66J0+RBe5VDf9B20uKDvfFO+Zpflk7Qqu8Xpd7EXgk4dxWep5olGnmKiEfJ1OOUk4yQH49HcNVIyiUvCgVUg9Sq6vpS/M4F34PUHhd8y6dMMVyhnHb3/hu5TF04c7jTPA==

  oidcSecretName: oidc-trek-secret
  encryptedOidcIssuer: AgDTVekKX1I8rTVpAQO/J/UqBvYMR16gfLQfDQIipUXHOFf/VBPyRqYIg6DU7hOLE5nMuKHtaV3VxMrKd2s9v/T5Y47IavrXiqiyRtKh6+lEd9sJIgMtl3PMulz63qj6+vtvUW1+vskAftHY298ZTNT9TNXZaTu+FLaV/8soMMYY5zHMgpk/tn1FyXWjv/bhr4Z0cZeDCNlIaXZ1K2/lfkt8+g6wlQIWDbiUIpfXvDsw2YLcESZHy9f+DTKVGJVXMUvgh2g7U9Ga22eRI7/KmKGbfvXDUpQT228ZLVHCMNTiY32aHXjEfmUeTDPkW9QDTLegodIPAuLHXveizBiS0xwfqfIszFVvqVRlr5fipKL2cAjNoZAnD7T5buJpJDQ8c91ScbxxBsBu6qvspuNhKcyeqXj3R5kSY4CFl1kYaJnwkXCioR4Cbd3x/RVfSmEH/234Szef4haoJIvCFAE9Cz1vWlYKHp5oXsIX8HuD/1aNV1mPbgqNwZYnGVF3LAIvGAuvVxFDr9YPH/WJHFvBmKdF1ijWbiIXexbUArD7sRD0bX8Mxm1+vazNlknmAdA7MtazzsJSNJggLrgJFToB+WM+CX/tTmBiEm0R56gxP2DDnz+E7aRn/Afg3rNm6wVLwxqOmLCFXgYc0lZT+ehNBgaFXEjgnDvHT2GhF/MIO8XuNCKBb39Cuu8+TBU81xBY6CUob9brVo4PJ9DuCbY2QZpZq6XCk/GpFRo8XoXzhSyJ9dA9OqLf61Mxeg==
  encryptedOidcClientId: AgDIWodl2yACXzMeUBTUawlWqaEYmIKmlrsjaC3O0JtyjIGR41Um0187WN3JqwrjNks/z0S+RHj7HFVwSR1suoo0yyK2zLOkAO99MwEtGxDyFyYwezKW4MJ7MQTgb/YXY7nEIGhMnjI/vQbCCJamirHspGqU0FM6eFaAzLbFB1DZbrPgGZgR8bWCl3lZx9vHSV7T1Fus0QvlZ+x5xWSh6uWbuu4wgndGLKYlsNJD4LvCS0ySedwYfUj3EtdNiZ3tJxda/C1HpXoSwjieBoZZIf8HEnPFrXj+YtQODN5DT19pTegVH1bmxws2lRVchF8ORGFfdiq/uOMDDGa4+mbr4CFReI8scIwwnA+qypWILR/ggPJ5D2F2EumbkAueYi1m4vwQ4BUIRl3eI2MpTr4rYJpMfQeK8mOZTiPB2htaOiv/fQ/xWynd1OC9IK+GVmjLuZtyYxawOaLmsU2eogCJSCYBr7Zq8SiHegAakvJafRMtTdgI7A8ND69TkBJVZcFaXCyLVk5qQYlM7WpJE7yYuissRy6w9mQqEgx887VhbOOXXb08B/zwS0JxRHiq8hnrN1f5EkdZcDBzdyXsN5gx8RfJZZtm30DSaRMiMhlsDxylQnsozKaafs28giwPjH8bX22hyMAFVJB8rpdhQiXfVlhjkqFupfiMN3TO1OrnWx7Oo04SekWUnD2Axqtit3F3aFYdb9TfwzLxUmVlNfbczZLWDo2Dl8RufCouHK3/I7sNOA==
  encryptedOidcClientSecret: AgBmrWeXVHCpEGJlYa6Wu2BMNYtNrFwtl2B7MqUh9onbtabrcvXph6dN/3QKeqy2gzzoXa6AQknvAhZL254e4tDx+GKyY64WvpM3g+HWWvPuyrrJbXwYbg76Odt+7ZmL70flWQ+09JWzw1vnZXCVMxK1c3hrN0I3naa5Oti6Ycg5YRPLBtko1F7/kw5H51EBEZ24wRCHSuMkCEz/Tp6JsQBAvLnEOyzMZ9XDQhiEF3wc/v/KVYYFn/kzEAtzFRF/1OM8W1SoFbgNJQ/6rAdeEWkvJ2/v6niCXTaS2EFD9Z9sU1WJpUzUatiSXqTbC5Dbsq1b3+Lm483OqIa9TL4aWBywHn1Q1f0dOjXN1wvklijPfmKRi/bFC99J/Akk2zpuvF9Isj7k6HNSe2r3Z5gZzDzk7BNpjcsOdkfgiqwWaX4nNEURSWq95p8SMte+Z5kq3nbfkIl2UrpAP1nhCf0BaKASufwa9m6q7cMzqSSZ3tJ68WvZ9Spnk761avq/YvNq+dn8aRPlcE4932DsgGtFLHNvGs7+h+SOGLfPWZaOLJb8s82qjHoMsUcOKnt59Sx0EwjE4iQdJvx8aP1O7mjw+zJb5c5yuoV4DRwaDJxV/NvLOnCuA32uxwx4GG06PdwZEMEJEDzjj2eHm0aMFeCTt9utfS4l6CPSgrAhnwB0bgoLq/4qPOgwnQu+5kkXCAdDbej3CGUeGW3oltWHml217Vl5GqzSdQu5AAUTfcYjSFoB86bXP3FH51Ex9nsOYNUzRw6fy7LtEYQIYGBZLmFTCSuJ
  encryptedOidcDisplayName: AgAt6HAx4K8TcMf9lJyjlrYbd4RqWwmvTPAOFXM4mK8toJZRagwLkHxsvTf1bBtLQv8zo9uTKH630QtrUfOWA/EGcmmMEUBHQNa8G7aP/ff2/ZJThD5omkHIs3ZqxyyhCshtSNvrJmx1Z2tYeAkYI5qx3fTvfyipR6kp2RqyMY2wX8q4Y4jiJUiP1OwihtsSESxVBMui+Aob28kKqzfMsIcAm7UzZTo0FDR+7WqSnzo1w/dDWotqgsclMxGAx+kX+Szsp7b2s2xSFpvAay3BV8yQCEtepslVoPw651MWWiHHFrZ9pQbTpQeF+zZ0Y5gYDAu8k4vjraJjsFJeKRpJhcWkMRrsMAvXM/k6GIK687hheB5zTi80iXG9BOFLJVIvvw97RSIQp+fOpRtgSe0QB1rv1u/px35McNuzxdLi3mVDn/57cP5bVCFddjFpa/Y7cVdAK0pZGPEBUERwsteADee3cG2YtnPEwFLX8R/QOywbaBsgz7KullbilmuOEcPuM+GiqDvsJfXIOWrwIGzVAXRi17zyW41Qih0WmYojRQFj71zQe4tjNeef8bvjfxsDYB2Lu2ACtub7HiQmfb605DaZ1GmJKfS6B3CMVCPGFX25F/6U9M2dVfA3pd/R3vg27IC0DKnjKiDaYrM0+bDWOFpOqvHbN2xdNjxueWgmaWSrhHFdTzCf1tNbuirqJO01tddQNlDrgg==
  encryptedOidcOnly: AgCUFEV9aBhkHaQW8zTys0e6vt8ci/Yo6mJr0Eidz2jxFB33mgKHlzixQuHfZRRefCAp4p2P90TBvScD6YX2NcM4rwx1HApjVA1Fz30+Kgk+x57TuZfAsUuyTLowyBwxXYTCRoyJQZQ+8GYwABVwpXDo20V/EygjLX3W/0Jt/ngb3pJOUC1eKQ9bkgLI4sMqZoBDyeK470XxruC4eoDsuo7X3GP3SRhuP2gcp3/ZZsdMhJrhcL/YQyAkdeecy1JyVaC8aAePsMkgLhVD5z6plf18sVXYzjvFb7HxoTE+6Kweuow3C342MUBzf/jmPyN7l0niOJXwnJWFEtd8dpfb4kiC4f5e+4uD8k6ji8lTM22nd9oIJtwx5PtEHcseEvL9lNdCsOktdj3GY69+bJAxJpFjKx+5+cZAkks8P0sMC8LglzEfgCq/a8dj5x/Og6w54bZZtcnlk0VsTZ7psHfTN7IKQtO81HfdPD8dX549SkcpvKITuMXQEhQUyKY+JStEvkue2wnkmW94bvU9wO0eH/5TJeMumBZigDQEJefNYcShMWz8ezeCML8xY19Y8G1XA/YIroPwdPN/st9JflgyMe6FhxWToGvdeiziKvW/e/qqCR6oqpCAa1pIPzQMeFRJRLR/Np+rF/dnIqJofqxsH7PBgvkjbJOwkniUsa49WN4iTroO/VqqMqgEmSm8grevR1TsbN1RRw==

pvc:
  dataPvcName: trek-data
  uploadPvcName: trek-uploads

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

postgresql:
  enabled: true
  architecture: replication

  auth:
    username: "trek"
    database: "trek"
    existingSecret: "trek-pg"
    secretKeys:
      adminPasswordKey: adminPasswordKey
      userPasswordKey: replicationPasswordKey
      replicationPasswordKey: userPasswordKey

  primary:
    persistence:
      size: 50Gi
    networkPolicy:
      allowExternal: false
      allowExternalEgress: false

  readReplicas:
    replicaCount: 1
    networkPolicy:
      allowExternal: false
      allowExternalEgress: false
